name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: alexey-1408
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/alexey-1408/Habit-Tracker
            docker-compose pull
            docker-compose up -d --build
