name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Run lint
      run: |
        flake8 .

    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.yml build

  deploy:
    needs: test_and_build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /path/to/project/on/server
          docker-compose pull
          docker-compose up -d --build
