version: "3.9"

services:
  web:
    build: .
    container_name: habit_web
    command: gunicorn habits_project.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: habit_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: habit_redis

  celery:
    build: .
    container_name: habit_celery
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: habit_celery_beat
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:1.25
    container_name: habit_nginx
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
