# Generated by Django 5.1.7 on 2025-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
