name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: habits_db
          POSTGRES_USER: anti
          POSTGRES_PASSWORD: 1234567890
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libcairo2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-django flake8

      - name: Run tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: habits_project.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "True"
          DB_NAME: habits_db
          DB_USER: anti
          DB_PASSWORD: 1234567890
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          # Ждём пока БД будет готова к подключению
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
          pytest --cov=. --cov-report=term-missing

      - name: Run flake8 lint
        run: flake8 .

      - name: Build Docker images
        run: docker compose build --no-cache

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/project/on/server
            docker compose pull
            docker compose up -d --build
