name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev openssh-client

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run flake8 linter
        run: flake8 .

      - name: Run tests with pytest
        run: pytest

      - name: Deploy to remote server
        if: github.ref == 'refs/heads/main' && success()
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d --build
